// import AppleIcon from './social/AppleIcon'
// import FacebookBgIcon from './social/FacebookBgIcon'
// import FacebookIcon from './social/FacebookIcon'
// import FacebookOutlineIcon from './social/FacebookOutlineIcon'
// import GoogleColorIcon from './social/GoogleColorIcon'
// import InstagramIcon from './social/InstagramIcon'
// import TwitterBgIcon from './social/TwitterBgIcon'
// import TwitterIcon from './social/TwitterIcon'
// import TwitterOutlineIcon from './social/TwitterOutlineIcon'

export * from './general/ConfettiIcon'
export * from './general/DollarIcon'
export * from './general/PersonPlusIcon'

export * from './culling'
export * from './edit'
export * from './enable'
export * from './general'
export * from './logo'
export * from './social'

// export {
// 	AddFolderIcon,
// 	AdjustmentIcon,
// 	AfterShootLogoIcon,
// 	AftershootEditIcon,
// 	AftershootLogoWhite,
// 	AlertCircleIcon,
// 	AlertFillIcon,
// 	AlertFillTriangleIcon,
// 	AlertHexagonBgIcon,
// 	AlertHexagonIcon,
// 	AlertTriangleBgIcon,
// 	AlertTriangleIcon,
// 	AppleIcon,
// 	ArrowDownIcon,
// 	ArrowFillRightIcon,
// 	ArrowFillUpIcon,
// 	ArrowLeftIcon,
// 	ArrowRightIcon,
// 	ArrowUpIcon,
// 	AtomBgIcon,
// 	BorderSquareIcon,
// 	CaptureOneIcon,
// 	CartIcon,
// 	CelebrateIcon,
// 	CheckBoxEmptyIcon,
// 	CheckBoxIcon,
// 	CheckBoxPartialIcon,
// 	CheckCircleBgIcon,
// 	CheckCircleIcon,
// 	CheckFillIcon,
// 	CheckIcon,
// 	ChevronDownIcon,
// 	ChevronLeftIcon,
// 	ChevronRightIcon,
// 	ChevronUpIcon,
// 	CircleFillIcon,
// 	CircleIcon,
// 	ClockIcon,
// 	CloseCircleIcon,
// 	CloseIcon,
// 	CollectionsIcon,
// 	ColorPaletteIcon,
// 	ComputerIcon,
// 	ConfettiLeftScreen,
// 	ConfettiRightScreen,
// 	ConfettiSideScreen,
// 	ContactSupportIcon,
// 	CopyContentIcon,
// 	CopyIcon,
// 	CouponIcon,
// 	CreateProfileIcon,
// 	CrossCircleIcon,
// 	CrossIcon,
// 	CrownBgIcon,
// 	CrownIcon,
// 	CullFromCardBgIcon,
// 	CullFromComputerBgIcon,
// 	CurveArrowIcon,
// 	DecrementIcon,
// 	DeleteBgIcon,
// 	DeleteIcon,
// 	DiamondIcon,
// 	DotsVerticalIcon,
// 	DragCaptureOneIcon,
// 	DragLrIcon,
// 	DragLrcIcon,
// 	DuplicateFillIcon,
// 	DuplicateIcon,
// 	EditAlbumNameIcon,
// 	EditIcon,
// 	EditPhotoIcon,
// 	EditProgressIcon,
// 	EditsLogoTextIcon,
// 	ExitAppBgIcon,
// 	ExpandIcon,
// 	ExportBgIcon,
// 	ExportIcon,
// 	EyeCheckedIcon,
// 	EyeCrossedIcon,
// 	EyeIcon,
// 	FacebookBgIcon,
// 	FacebookIcon,
// 	FacebookOutlineIcon,
// 	FacebookPeopleIcon,
// 	FailFillBgIcon,
// 	FailFillIcon,
// 	FileSearchIcon,
// 	FilterCircleIcon,
// 	FilterIcon,
// 	FiveStarBgIcon,
// 	FlagFillIcon,
// 	FlagOutlineCrossedIcon,
// 	FlagOutlineIcon,
// 	FolderFillIcon,
// 	FolderOutlineBgIcon,
// 	FolderOutlineCrossedIcon,
// 	GlobalIcon,
// 	GoogleColorIcon,
// 	GridBgIcon,
// 	GridDotsIcon,
// 	GridThreeLitIcon,
// 	GridTwoLitIcon,
// 	GroupingLessIcon,
// 	GroupingMoreIcon,
// 	HomeIcon,
// 	ImageBorderCircleIcon,
// 	ImageBorderIcon,
// 	ImageCrossedBgIcon,
// 	ImageCrossedIcon,
// 	InfoBgIcon,
// 	InfoCircleIcon,
// 	InstagramIcon,
// 	KeyCircleIcon,
// 	KeyIcon,
// 	LightroomClassicIcon,
// 	LightroomIcon,
// 	LinkIcon,
// 	ListNotSelectedIcon,
// 	ListSelectedIcon,
// 	LoaderIcon,
// 	LockIcon,
// 	LoopIcon,
// 	LoupeIcon,
// 	MaximizeIcon,
// 	MenuIcon,
// 	MinimizeIcon,
// 	MoneyBagIcon,
// 	MoodIcon,
// 	MouseLeftClick,
// 	MouseLeftClickCircleIcon,
// 	MouseRightClick,
// 	MoveBgIcon,
// 	NoDuplicateIcon,
// 	NoneIcon,
// 	NoneSelectedIcon,
// 	NotAllowIcon,
// 	OpenlinkIcon,
// 	PersonIcon,
// 	PipeIcon,
// 	PlayBgIcon,
// 	PlayCircleIcon,
// 	PlusBgIcon,
// 	PowerHighIcon,
// 	PowerLowIcon,
// 	PowerMidIcon,
// 	ProcessIcon,
// 	QuestionMarkCircleIcon,
// 	QuestionMarkIcon,
// 	RecullIcon,
// 	RefreshIcon,
// 	ReloadIcon,
// 	RevertIcon,
// 	RightArrowBgIcon,
// 	RotateIcon,
// 	ScissorsIcon,
// 	SearchIcon,
// 	SelectedCircleBgIcon,
// 	ShareIcon,
// 	ShowDuplicateIcon,
// 	SmileyHappyIcon,
// 	SmileySadIcon,
// 	SortCircleIcon,
// 	SortDuplicateCircleIcon,
// 	SortDuplicatesIcon,
// 	SortIcon,
// 	SortOptionAlphaIcon,
// 	SortOptionNumIcon,
// 	SparkleIcon,
// 	SprayBgIcon,
// 	SprayCanIcon,
// 	SprayCircleIcon,
// 	Stack2Icon,
// 	StackIcon,
// 	StarCrossedIcon,
// 	StarIcon,
// 	StorageCrossedIcon,
// 	SuccessFillBgIcon,
// 	ThumbDownBgIcon,
// 	ThumbUpBgIcon,
// 	ThunderBgIcon,
// 	TwitterBgIcon,
// 	TwitterIcon,
// 	TwitterOutlineIcon,
// 	UploadBgIcon,
// 	UploadCloudBgIcon,
// 	UploadCloudIcon,
// 	UploadFolderIcon,
// 	ViewAllIcon,
// 	WifiCrossedBgIcon,
// 	WifiCrossedIcon,
// 	ZoomCircleIcon,
// 	ZoomIcon,
// }
