const DEFAULT_ICON_COLOR = '#fff'
const DEFAULT_ICON_SIZE = 24

const DEFAULT_ICON_INACTIVE_COLOR = '#777777'
const DEFAULT_ICON_FILL_COLOR = '#3B5998'
const DEFAULT_ICON_ACCENT_COLOR = '#2279CE'
const DEFAULT_ICON_CIRCLE_OPACITY = 0.5
const DEFAULT_ICON_OUTLINE_COLOR = '#E2E2E2'

const DEFAULT_ICON_BG_SIZE = 40
const DEFAULT_ICON_BG_COLOR = '#555555'

const DEFAULT_ICON_BORDER_RADIUS = 50
const DEFAULT_ICON_BORDER_WIDTH = 2
const DEFAULT_ICON_BORDER_COLOR = '#555555'
const DEFAULT_ICON_BORDER_PADDING = 40
// const DEFAULT_ICON_BORDER_OPACITY = 0.25

const DEFAULT_ICON = {
	COLOR: DEFAULT_ICON_COLOR,
	INACTIVE_COLOR: DEFAULT_ICON_INACTIVE_COLOR,
	SIZE: DEFAULT_ICON_SIZE,
	BG_COLOR: DEFAULT_ICON_BG_COLOR,
	FILL_COLOR: DEFAULT_ICON_FILL_COLOR,
	ACCENT_COLOR: DEFAULT_ICON_ACCENT_COLOR,
	CIRCLE_OPACITY: DEFAULT_ICON_CIRCLE_OPACITY,
	OUTLINE_COLOR: DEFAULT_ICON_OUTLINE_COLOR,
	BG_SIZE: DEFAULT_ICON_BG_SIZE,
	BORDER_RADIUS: DEFAULT_ICON_BORDER_RADIUS,
	BORDER_WIDTH: DEFAULT_ICON_BORDER_WIDTH,
	BORDER_COLOR: DEFAULT_ICON_BORDER_COLOR,
	BORDER_SIZE: DEFAULT_ICON_BORDER_PADDING,
}

export default DEFAULT_ICON
